### ISSUE TITLE
Exception is thrown when object with no setters is mapped to.

### ISSUE THREAD

**Issue by eswann** [eswann/Mapster#33]
I have an object that is populated via the constructor, so the properties have no setters (not even private ones).  Mapping to this object causes a failure.  The workaround is to add private setters, but would be nice if it's not necessary to have these as it clutters the objects.

**Comment by chaowlert** [comment]
This is because I treat immutable object as primitives. It cannot be destination. My scenario is when I use Url and DbGeography as properties in v1. I will got error on transformation.

But how you expect Mapster to work? Mapster doesn't support map to constructor yet. At this time, you could use MapWith to map manually, and then model can have no setter.

**Comment by eswann** [comment]
In this case, I'm constructing using ConstructUsing(src => new dest(src.x, src.y, src.z...)) to set up the constructor.  MapWith would just be a replacement...sounds good.

**Comment by chaowlert** [comment]
Another idea to solve if you have a lot of record types to map. You can create new adapter inherit from BaseAdapter. I haven't put this into document as it is a bit advance.

The class will need to override Priority method to determine which type pair will map with the adapter. If it cannot map, it should return null, otherwise return priority.
You can also override CanInline method to always return true, because map to record type can use only one line.
After that you can override CreateInlineExpression, and put logic to create your mapping there.

After you finish, you can register by TypeAdapterConfig.GlobalSettings.Rules.Add(new YourAdapter().CreateRule()).

After that Mapster should be able to map record type. This could be starting point to support #28 and it also be starting point to support third party add-in in the future.

**Comment by eswann** [comment]
I'm closing this per this issue being solved by MapTo and @chaowlert adding #37  for better messages
