### ISSUE TITLE
Consider making TypeAdapterConfig internal state immutable

### ISSUE THREAD

**Issue by eswann** [eswann/Mapster#41]
I need a way to clone the global typeadapterconfig for an instance config and make it efficient.

Here is the scenario:  I have all of my global configuration set for my app.  I want to inject an IAdapter per scope that inherits from the global config but adds an adapter rule just for that adapter instance because it's dependent on an item that's injected.  If the internal state of the TypeAdapterConfig was comprised of immutable collections, it would make clone operations very fast and updates to the resultant config would not impact the global config.
@chaowlert if you have any ideas on this, would be appreciated.

**Comment by chaowlert** [comment]
This is part of plan for Mapster 3.0. I also would like to do inline config, we need clone functionality anyway. I don't want inline config to change state of external config.

To make TypeAdapterConfig collection to be immutable, my concern is, even collection is immutable, but Setting inside is not. Otherwise, we also need to change Setting to be immutable. My original thought is, we just do deep clone to clone config.
