### ISSUE TITLE
Compile() errors on config.NewConfig<TimeSpan, int>() 

### ISSUE THREAD

**Issue by kellyethridge** [eswann/Mapster#62]
Hello,
First thank you for the great library!

I've got the mapping `config.NewConfig<TimeSpan, int>().MapWith(t => (int)t.TotalSeconds);` that does work. However when I try to validate all the mappings by calling Compile(), it throws 

> Expression of type 'System.TimeSpan' cannot be used for parameter of type 'System.Object' of method 'Int32 ToInt32(System.Object)'

for `config.NewConfig<TimeSpan, int>()`. It compiles fine for the mapping in the other direction `config.NewConfig<int, TimeSpan>()`.

So, I'm currently skipping validation of the mappings. Is it a fluke that this mapping works or does the validation have an error in it?

**Comment by chaowlert** [comment]
@kellyethridge I cannot reproduce. I might not fully understand what you describe but with following code. It works.

```
TypeAdapterConfig.GlobalSettings.NewConfig<TimeSpan, int>().MapWith(t => (int) t.TotalSeconds);
TypeAdapterConfig.GlobalSettings.Compile();
```

Anyway, it is possible that you can map successfully, but validation fail. It might be because query projection fail. Validation validates both mapping and projection. In the future, I might add option to compile only selected types (mapping or projection or both).

**Comment by kellyethridge** [comment]
You are right. I had an old version referenced for some reason. Thank you for checking it out! I'll close this.
