### ISSUE TITLE
Mapping with attributes which raise exceptions

### ISSUE THREAD

**Issue by alexeyosipov** [eswann/Mapster#93]
Don't really know if it is a bug or expected behavior. But if I have a class with attribute for it's property:

```
class A
{
    [Erroneous]
    public int X {get;set;}
}
```

where given attribute raises exception in constructor like here:

```
public sealed class ErroneousAttribute : System.ComponentModel.DisplayNameAttribute
{
    public ErroneousAttribute()
    {
        throw new Exception();
    }
}
```

so in this case `TypeAdapter.Adapt<A, A>(new A());` will lead to error, like if constructor was called for every attribute.

**Comment by chaowlert** [comment]
Attributes will be instantiated when there is a call to `GetCustomAttributes`, this is default behavior of .NET. Attributes should represent meta-data not control flow, your `ErroneousAttribute` should not throw on instantiation. Even Mapster handles for you, you will found similar issue in other libraries.

Sorry, I will close this issue, since, it is not in scope of `Mapster`.
